# Generated by Django 4.2.7 on 2023-11-14 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='facebook',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Nhập đúng format url', regex='^(https?://)?(www\\.)?[a-zA-Z0-9-]+\\.[a-zA-Z]{2,}(\\/\\S*)?$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Nhập đúng format số điện thoại', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
