# Generated by Django 4.2.7 on 2023-11-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='', verbose_name='/vol/web/media')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('size', models.CharField(choices=[('XS', 'XS'), ('X', 'X'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='XS', max_length=20)),
                ('color', models.CharField(default='Trắng', max_length=100)),
                ('condition', models.CharField(default='New Tag', max_length=20)),
                ('original_price', models.IntegerField(default=0)),
                ('bought_price', models.IntegerField(default=0)),
                ('status', models.SmallIntegerField(default=0)),
                ('bought_date_time', models.DateTimeField(null=True)),
                ('sell_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RentingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_renting', models.CharField(choices=[('1 Ngày', '1 Ngày'), ('3 Ngày', '3 Ngày')], default='1 Ngày', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
