# Generated by Django 4.2.7 on 2023-11-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="type",
            field=models.SmallIntegerField(
                choices=[(0, "Thuê"), (1, "Mua")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Đang chờ"),
                    (1, "Đã xác nhận"),
                    (2, "Đang giao"),
                    (3, "Đã giao"),
                    (4, "Đã hủy"),
                ],
                default=0,
            ),
        ),
    ]
